export const reactQues = [
  "What is JSX?",
  "When to use a Class Component over a Function Component?",
  "What is state in React?",
  "What are Pure Components?",
  "What are props in React?",
  "What is the difference between state and props?",
  "Why should we not update the state directly?",
  "What is key prop and what is the benefit of using it in arrays of elements?",
  "What is the use of refs?",
  "What is React Riber?",
  "What is Virtual DOM?",
  "What is React Potal?",
  "What are Higher-Order components?",
  "What is reconciliation?",
  "What are fragments?",
  "What is React Native and how does it differ from React?",
  "How do you handle navigation between screens in React Native?",
  "Explain the concept of 'flexbox' and its role in React Native layout.",
  "Describe the purpose of 'AsyncStorage' in React Native.",
  "How do you optimize performance in a React Native application?",
  "How to use Redux?",
  "How to handle theme modes in React Native?",
  "How do you handle platform-specific code in React Native?",
  "How do you handle push notifications in a React Native app?",
  "Describe the bridge communication in React Native.",
  "Explain the use of 'native modules' in React Native.",
  "Explain hooks in React",
  "How useCallback is different from useMemo?",
  "How to avoid unnecessary rerendering in React?",
  "Difference between FlatList and ScrollView?",
  "What are ES6 features?",
  "Difference between Rest & Spread operator in JS?",
];
